In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Patient_appointments_dataset.csv')

In [3]:
df.head(20)

PatientId  AppointmentID Gender          ScheduledDay  \
0   2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1   5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2   4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3   8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4   8.841186e+12        5642494      F  2016-04-29T16:07:23Z   
5   9.598513e+13        5626772      F  2016-04-27T08:36:51Z   
6   7.336882e+14        5630279      F  2016-04-27T15:05:12Z   
7   3.449833e+12        5630575      F  2016-04-27T15:39:58Z   
8   5.639473e+13        5638447      F  2016-04-29T08:02:16Z   
9   7.812456e+13        5629123      F  2016-04-27T12:48:25Z   
10  7.345362e+14        5630213      F  2016-04-27T14:58:11Z   
11  7.542951e+12        5620163      M  2016-04-26T08:44:12Z   
12  5.666548e+14        5634718      F  2016-04-28T11:33:51Z   
13  9.113946e+14        5636249      M  2016-04-28T14:52:07Z   
14  9.988472e+13        5633951      F  2016-04-28T10:06:24Z   
15  9.994839e+10        5620206      F  2016-04-26T08:47:27Z   
16  8.457439e+13        5633121      M  2016-04-28T08:51:47Z   
17  1.479497e+13        5633460      F  2016-04-28T09:28:57Z   
18  1.713538e+13        5621836      F  2016-04-26T10:54:18Z   
19  7.223289e+12        5640433      F  2016-04-29T10:43:14Z   

          AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0   2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1   2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2   2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3   2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4   2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   
5   2016-04-29T00:00:00Z   76          REPÚBLICA            0             1   
6   2016-04-29T00:00:00Z   23         GOIABEIRAS            0             0   
7   2016-04-29T00:00:00Z   39         GOIABEIRAS            0             0   
8   2016-04-29T00:00:00Z   21         ANDORINHAS            0             0   
9   2016-04-29T00:00:00Z   19          CONQUISTA            0             0   
10  2016-04-29T00:00:00Z   30     NOVA PALESTINA            0             0   
11  2016-04-29T00:00:00Z   29     NOVA PALESTINA            0             0   
12  2016-04-29T00:00:00Z   22     NOVA PALESTINA            1             0   
13  2016-04-29T00:00:00Z   28     NOVA PALESTINA            0             0   
14  2016-04-29T00:00:00Z   54     NOVA PALESTINA            0             0   
15  2016-04-29T00:00:00Z   15     NOVA PALESTINA            0             0   
16  2016-04-29T00:00:00Z   50     NOVA PALESTINA            0             0   
17  2016-04-29T00:00:00Z   40          CONQUISTA            1             0   
18  2016-04-29T00:00:00Z   30     NOVA PALESTINA            1             0   
19  2016-04-29T00:00:00Z   46           DA PENHA            0             0   

    Diabetes  Alcoholism  Handcap  SMS_received No-show  
0          0           0        0             0      No  
1          0           0        0             0      No  
2          0           0        0             0      No  
3          0           0        0             0      No  
4          1           0        0             0      No  
5          0           0        0             0      No  
6          0           0        0             0     Yes  
7          0           0        0             0     Yes  
8          0           0        0             0      No  
9          0           0        0             0      No  
10         0           0        0             0      No  
11         0           0        0             1     Yes  
12         0           0        0             0      No  
13         0           0        0             0      No  
14         0           0        0             0      No  
15         0           0        0             1      No  
16         0    

### Let's take a look into our data.

In [4]:
df.shape

(110527, 14)

Looks like we have 100000 rows.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64  
 2   Gender          110527 non-null  object 
 3   ScheduledDay    110527 non-null  object 
 4   AppointmentDay  110527 non-null  object 
 5   Age             110527 non-null  int64  
 6   Neighbourhood   110527 non-null  object 
 7   Scholarship     110527 non-null  int64  
 8   Hipertension    110527 non-null  int64  
 9   Diabetes        110527 non-null  int64  
 10  Alcoholism      110527 non-null  int64  
 11  Handcap         110527 non-null  int64  
 12  SMS_received    110527 non-null  int64  
 13  No-show         110527 non-null  object 
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


In [6]:
df.describe()

PatientId  AppointmentID            Age    Scholarship  \
count  1.105270e+05   1.105270e+05  110527.000000  110527.000000   
mean   1.474963e+14   5.675305e+06      37.088874       0.098266   
std    2.560949e+14   7.129575e+04      23.110205       0.297675   
min    3.921784e+04   5.030230e+06      -1.000000       0.000000   
25%    4.172614e+12   5.640286e+06      18.000000       0.000000   
50%    3.173184e+13   5.680573e+06      37.000000       0.000000   
75%    9.439172e+13   5.725524e+06      55.000000       0.000000   
max    9.999816e+14   5.790484e+06     115.000000       1.000000   

        Hipertension       Diabetes     Alcoholism        Handcap  \
count  110527.000000  110527.000000  110527.000000  110527.000000   
mean        0.197246       0.071865       0.030400       0.022248   
std         0.397921       0.258265       0.171686       0.161543   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       4.000000   

        SMS_received  
count  110527.000000  
mean        0.321026  
std         0.466873  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [7]:
df['Diabetes'].value_counts()


0    102584
1      7943
Name: Diabetes, dtype: int64

In [8]:
df['No-show'].value_counts()

No     88208
Yes    22319
Name: No-show, dtype: int64

In [9]:
df['Handcap'].value_counts()

0    108286
1      2042
2       183
3        13
4         3
Name: Handcap, dtype: int64

In [10]:
df['Neighbourhood'].value_counts()

JARDIM CAMBURI                 7717
MARIA ORTIZ                    5805
RESISTÊNCIA                    4431
JARDIM DA PENHA                3877
ITARARÉ                        3514
                               ... 
ILHA DO BOI                      35
ILHA DO FRADE                    10
AEROPORTO                         8
ILHAS OCEÂNICAS DE TRINDADE       2
PARQUE INDUSTRIAL                 1
Name: Neighbourhood, Length: 81, dtype: int64

As we can see [	Scholarship	Hipertension, Diabetes, Alcoholism, SMS_received, No-show] are all boolean types (1,0 or yes,no) values except the ['Handcap'] which has 5 different values, this may indicates how severe is the handicap.

## Data Cleaning and Preprocessing

There's some useless columns like _PatientId, AppointmentID and ScheduledDay_ so we will drop these columns

In [11]:
df.drop(['PatientId', 'AppointmentID', 'ScheduledDay'],axis=1, inplace=True)

In [12]:
df.head()

Gender        AppointmentDay  Age      Neighbourhood  Scholarship  \
0      F  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0   
1      M  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   
2      F  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0   
3      F  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0   
4      F  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0   

   Hipertension  Diabetes  Alcoholism  Handcap  SMS_received No-show  
0             1         0           0        0             0      No  
1             0         0           0        0             0      No  
2             0         0           0        0             0      No  
3             0         0           0        0             0      No  
4             1         1           0        0             0      No

Checking for null values.

In [13]:
df.isna().sum()

Gender            0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

### Let's have a look at *Age* column and its different values.

In [14]:
df['Age'].value_counts()

 0      3539
 1      2273
 52     1746
 49     1652
 53     1651
        ... 
 115       5
 100       4
 102       2
 99        1
-1         1
Name: Age, Length: 104, dtype: int64

looks like we have an invalid data which is -1 , So we will remove that entry.

In [15]:
invalid_entry = df[df['Age'] < 0]
df.drop(invalid_entry.index, inplace=True)
df[df['Age'] < 0]

Empty DataFrame
Columns: [Gender, AppointmentDay, Age, Neighbourhood, Scholarship, Hipertension, Diabetes, Alcoholism, Handcap, SMS_received, No-show]
Index: []

In [16]:
df['Age'].value_counts()

0      3539
1      2273
52     1746
49     1652
53     1651
       ... 
98        6
115       5
100       4
102       2
99        1
Name: Age, Length: 103, dtype: int64

In [17]:
# now lets drop duplicate entries... 
df.drop_duplicates(inplace=True)
df.shape

(95151, 11)

### We removed more than 10k duplicated entries. approximately 10% of our whole dataset.

Since we don't want the exact time of the appointment date we will cut it from the full time stamp.

In [18]:
df['AppointmentDay'] = df['AppointmentDay'].apply(lambda x: x.split("T")[0])


In [19]:
df['AppointmentDay'].head(15)

0     2016-04-29
1     2016-04-29
2     2016-04-29
3     2016-04-29
4     2016-04-29
5     2016-04-29
6     2016-04-29
7     2016-04-29
8     2016-04-29
9     2016-04-29
10    2016-04-29
11    2016-04-29
12    2016-04-29
13    2016-04-29
14    2016-04-29
Name: AppointmentDay, dtype: object

Now lets rename the columns into something better and informative. also correct some spelling errors.

In [20]:
df.head()

Gender AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0      F     2016-04-29   62    JARDIM DA PENHA            0             1   
1      M     2016-04-29   56    JARDIM DA PENHA            0             0   
2      F     2016-04-29   62      MATA DA PRAIA            0             0   
3      F     2016-04-29    8  PONTAL DE CAMBURI            0             0   
4      F     2016-04-29   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No  
4         1           0        0             0      No

In [21]:
df = df.rename(columns={'AppointmentDay': 'Appointment_Date', 'Hipertension': 'Hypertension', 'Handcap': 'Handicap' })


In [22]:
df.head()

Gender Appointment_Date  Age      Neighbourhood  Scholarship  Hypertension  \
0      F       2016-04-29   62    JARDIM DA PENHA            0             1   
1      M       2016-04-29   56    JARDIM DA PENHA            0             0   
2      F       2016-04-29   62      MATA DA PRAIA            0             0   
3      F       2016-04-29    8  PONTAL DE CAMBURI            0             0   
4      F       2016-04-29   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handicap  SMS_received No-show  
0         0           0         0             0      No  
1         0           0         0             0      No  
2         0           0         0             0      No  
3         0           0         0             0      No  
4         1           0         0             0      No

Let's convert our date into datetime so we can perform any other needed method.

In [23]:
df['Appointment_Date'] = pd.to_datetime(df['Appointment_Date'])
df['Appointment_Date'].head()

0   2016-04-29
1   2016-04-29
2   2016-04-29
3   2016-04-29
4   2016-04-29
Name: Appointment_Date, dtype: datetime64[ns]

Now we will extract the Week day from the converted Date easily.

In [24]:
df['Weekday'] = df['Appointment_Date'].dt.day_name()
df['Weekday'].head(15)

0     Friday
1     Friday
2     Friday
3     Friday
4     Friday
5     Friday
6     Friday
7     Friday
8     Friday
9     Friday
10    Friday
11    Friday
12    Friday
13    Friday
14    Friday
Name: Weekday, dtype: object

In [25]:
df.head()

Gender Appointment_Date  Age      Neighbourhood  Scholarship  Hypertension  \
0      F       2016-04-29   62    JARDIM DA PENHA            0             1   
1      M       2016-04-29   56    JARDIM DA PENHA            0             0   
2      F       2016-04-29   62      MATA DA PRAIA            0             0   
3      F       2016-04-29    8  PONTAL DE CAMBURI            0             0   
4      F       2016-04-29   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handicap  SMS_received No-show Weekday  
0         0           0         0             0      No  Friday  
1         0           0         0             0      No  Friday  
2         0           0         0             0      No  Friday  
3         0           0         0             0      No  Friday  
4         1           0         0             0      No  Friday

In [26]:
df.isna().sum()

Gender              0
Appointment_Date    0
Age                 0
Neighbourhood       0
Scholarship         0
Hypertension        0
Diabetes            0
Alcoholism          0
Handicap            0
SMS_received        0
No-show             0
Weekday             0
dtype: int64

### now let's check and convert the data types into ones that are compatible with machine learing models and libraries.

In [27]:
attrs = ['Neighbourhood', 'No-show','Gender' ]

df[attrs] = df [attrs].apply(lambda x: pd.factorize(x)[0] + 1)

In [28]:
df.head()

Gender Appointment_Date  Age  Neighbourhood  Scholarship  Hypertension  \
0       1       2016-04-29   62              1            0             1   
1       2       2016-04-29   56              1            0             0   
2       1       2016-04-29   62              2            0             0   
3       1       2016-04-29    8              3            0             0   
4       1       2016-04-29   56              1            0             1   

   Diabetes  Alcoholism  Handicap  SMS_received  No-show Weekday  
0         0           0         0             0        1  Friday  
1         0           0         0             0        1  Friday  
2         0           0         0             0        1  Friday  
3         0           0         0             0        1  Friday  
4         1           0         0             0        1  Friday

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95151 entries, 0 to 110525
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Gender            95151 non-null  int64         
 1   Appointment_Date  95151 non-null  datetime64[ns]
 2   Age               95151 non-null  int64         
 3   Neighbourhood     95151 non-null  int64         
 4   Scholarship       95151 non-null  int64         
 5   Hypertension      95151 non-null  int64         
 6   Diabetes          95151 non-null  int64         
 7   Alcoholism        95151 non-null  int64         
 8   Handicap          95151 non-null  int64         
 9   SMS_received      95151 non-null  int64         
 10  No-show           95151 non-null  int64         
 11  Weekday           95151 non-null  object        
dtypes: datetime64[ns](1), int64(10), object(1)
memory usage: 9.4+ MB


In [30]:
df= pd.get_dummies(df)

In [33]:
df.head()

Gender Appointment_Date  Age  Neighbourhood  Scholarship  Hypertension  \
0       1       2016-04-29   62              1            0             1   
1       2       2016-04-29   56              1            0             0   
2       1       2016-04-29   62              2            0             0   
3       1       2016-04-29    8              3            0             0   
4       1       2016-04-29   56              1            0             1   

   Diabetes  Alcoholism  Handicap  SMS_received  No-show  Weekday_Friday  \
0         0           0         0             0        1               1   
1         0           0         0             0        1               1   
2         0           0         0             0        1               1   
3         0           0         0             0        1               1   
4         1           0         0             0        1               1   

   Weekday_Monday  Weekday_Saturday  Weekday_Thursday  Weekday_Tuesday  \
0               0                 0                 0                0   
1               0                 0                 0                0   
2               0                 0                 0                0   
3               0                 0                 0                0   
4               0                 0                 0                0   

   Weekday_Wednesday  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [34]:
df.info()   

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95151 entries, 0 to 110525
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   Gender             95151 non-null  int64         
 1   Appointment_Date   95151 non-null  datetime64[ns]
 2   Age                95151 non-null  int64         
 3   Neighbourhood      95151 non-null  int64         
 4   Scholarship        95151 non-null  int64         
 5   Hypertension       95151 non-null  int64         
 6   Diabetes           95151 non-null  int64         
 7   Alcoholism         95151 non-null  int64         
 8   Handicap           95151 non-null  int64         
 9   SMS_received       95151 non-null  int64         
 10  No-show            95151 non-null  int64         
 11  Weekday_Friday     95151 non-null  uint8         
 12  Weekday_Monday     95151 non-null  uint8         
 13  Weekday_Saturday   95151 non-null  uint8         
 14  Weekd

In [35]:
df['No-show'].value_counts()

1    74458
2    20693
Name: No-show, dtype: int64

### No is 1

### Yes is 2

Now that the data is prepared we can work on the machine learning models and experiment different models.

## Model Building and experimenting

In [36]:
# Import some classification models
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier

# import needed functions
from sklearn.model_selection import cross_validate
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.metrics import f1_score

In [37]:
x = df.drop(['No-show', 'Appointment_Date'] , axis=1)
y = df['No-show']


In [38]:
x.head()

Gender  Age  Neighbourhood  Scholarship  Hypertension  Diabetes  \
0       1   62              1            0             1         0   
1       2   56              1            0             0         0   
2       1   62              2            0             0         0   
3       1    8              3            0             0         0   
4       1   56              1            0             1         1   

   Alcoholism  Handicap  SMS_received  Weekday_Friday  Weekday_Monday  \
0           0         0             0               1               0   
1           0         0             0               1               0   
2           0         0             0               1               0   
3           0         0             0               1               0   
4           0         0             0               1               0   

   Weekday_Saturday  Weekday_Thursday  Weekday_Tuesday  Weekday_Wednesday  
0                 0                 0                0                  0  
1                 0                 0                0                  0  
2                 0                 0                0                  0  
3                 0                 0                0                  0  
4                 0                 0                0                  0

In [39]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: No-show, dtype: int64

In [40]:
y.shape

(95151,)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)
# random_state is recommended to used the parameter (random_state=42) to produce the same results across a different runs.

In [76]:
RF = RandomForestClassifier()
results = cross_validate(RF, x, y, cv=5, scoring='accuracy', return_train_score=True)
print('Randdom forest')
print("Accuracy:" , 'train: ', results['train_score'].mean(), '/// test: ', results['test_score'].mean())


Randdom forest
Accuracy: train:  0.9047513959214049 | test:  0.7124675753057496
---------------------------------------------------------


In [86]:
DT = DecisionTreeClassifier()
results = cross_validate(DT, x, y, cv=5, scoring='accuracy', return_train_score=True)
print('DecisionTree: ')
print("Accuracy: train: " , results['train_score'].mean(), '/// test: ', results['test_score'].mean())



DecisionTree: 
Accuracy: train:  0.9047986891158567 | test:  0.6859728010219132


In [42]:
SVClassifier = SVC()
results = cross_validate(SVClassifier, x, y, cv=5, scoring='accuracy', return_train_score=True)
print('Support vector machine: ')
print("Accuracy: train: " , results['train_score'].mean(), '/// test: ', results['test_score'].mean())


Support vector machine: 
Accuracy: train:  0.7825246187716609 | test:  0.7825246188886772


# ---------------


In [1]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Random Forest Accuracy is =', accuracy_score(y_test, y_preds))


NameError: name 'RandomForestClassifier' is not defined

In [44]:
cm_RF = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Random Forest : \n')
print(cm_RF)

Confusion Matrix for Random Forest : 

[[6542  980]
 [1696  298]]


In [45]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.6944091612645361

In [46]:
 model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Decision Tree Accuracy is =', accuracy_score(y_test, y_preds))



Decision Tree Accuracy is = 0.6953551912568307


In [47]:
cm_DT = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Decision Tree : \n')
print(cm_DT)

Confusion Matrix for Decision Tree : 

[[6249 1273]
 [1626  368]]


In [48]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.6840551730868866

In [49]:
 model = SVC()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_preds))

# View a list of the features and their importance scores


Accuracy: 0.7904581757040774


Looks like the support vector classifier has bested the RandomForest and the decision tree. It also has a reasonable accuracy.

In [50]:
cm_SVC = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Support Vector Machine : \n')
print(cm_SVC)

Confusion Matrix for Support Vector Machine : 

[[7522    0]
 [1994    0]]


In [51]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.6979488669616234

In [52]:
 model = GradientBoostingClassifier()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_preds))

Accuracy: 0.7905632618747372


In [53]:
cm_GB = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Gradient Boosting  : \n')
print(cm_GB)

Confusion Matrix for Gradient Boosting  : 

[[7522    0]
 [1993    1]]


In [54]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.698199900606387

In [55]:
 model = LogisticRegression()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_preds))

Accuracy: 0.7904581757040774
C:\Users\s7kin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [58]:
cm_LR = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Logistic regression  : \n')
print(cm_LR)

Confusion Matrix for Logistic regression  : 

[[7522    0]
 [1994    0]]


In [59]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.6979488669616234

as we can see the models are strongly going to Positive choices (TP and FN). maybe this is where the deep learning gets handy.

In [60]:
 model = GaussianNB()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_preds))

Accuracy: 0.7832072299285414


In [61]:
cm_GNB = metrics.confusion_matrix(y_test, y_preds)
print('Confusion Matrix for Gaussian NB  : \n')
print(cm_GNB)

Confusion Matrix for Gaussian NB  : 

[[7365  157]
 [1906   88]]


We finally got a reasonable decision making model. and not one that always goes to The positive predictions (TP and FN). i will be picking this model as my final model.

In [65]:
print(' the F1 score is : ')
f1_score(y_test, y_preds, average='weighted')


 the F1 score is : 


0.7098226863495837

As we can see it has the highest F1 score.

AUC for the selected model:

In [62]:
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_preds, pos_label=2)
metrics.auc(fpr, tpr)

0.511630144354894

In [66]:
import pickle
pickle.dump(model, open('model_GNB.pkl','wb'))
